#服务类配置
server:
  port: 8080
  servlet:
    session:
      timeout:30m #30分钟，超时


spring:
  application:
    name: GspringbService #springboot的应用名






#自定义配置
gspring:
  key1: gpringk1
spring.mvc.pathmatch.matching-strategy:
  ANT_PATH_MATCHER
